hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

itk_jira:
    resource: "@ItkJiraBundle/Controller/"
    type:     annotation

jira_login:
    path: /login/check-jira